/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.personaje;

import java.awt.Image;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author dam2_alu08@inf.ald
 */
public class PersonajeDialog extends javax.swing.JDialog {

    /**
     * Creates new form PersonajeDialog
     */
    public PersonajeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idComboBox = new javax.swing.JComboBox<>();
        idLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        speciesLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        originLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        idLabel.setText("ID");

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        imageLabel.setText(" ");

        nameLabel.setText(" ");

        statusLabel.setText(" ");

        speciesLabel.setText(" ");

        typeLabel.setText(" ");

        genderLabel.setText(" ");

        originLabel.setText(" ");

        locationLabel.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(idLabel)
                        .addGap(42, 42, 42)
                        .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusLabel)
                            .addComponent(speciesLabel)
                            .addComponent(locationLabel)
                            .addComponent(genderLabel)
                            .addComponent(typeLabel)
                            .addComponent(originLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(320, 320, 320)
                                .addComponent(nameLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addComponent(imageLabel)))))
                .addContainerGap(370, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(statusLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speciesLabel)
                    .addComponent(imageLabel))
                .addGap(18, 18, 18)
                .addComponent(typeLabel)
                .addGap(18, 18, 18)
                .addComponent(genderLabel)
                .addGap(18, 18, 18)
                .addComponent(originLabel)
                .addGap(18, 18, 18)
                .addComponent(locationLabel)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTextNameLabel(String s) {
        this.nameLabel.setText(s);
    }

    public void setTextStatusLabel(String s) {
        this.statusLabel.setText(s);
    }

    public void setTextSpeciesLabel(String s) {
        this.speciesLabel.setText(s);
    }

    public void setTextTypeLabel(String s) {
        this.typeLabel.setText(s);
    }
    
    public void setTextGenderLabel(String s) {
        this.genderLabel.setText(s);
    }
    
    public void setTextOriginLabel(String s) {
        this.originLabel.setText(s);
    }
    
    public void setTextLocationLabel(String s) {
        this.locationLabel.setText(s);
    }
    
    public void setIconImageLabel(String s) throws IOException{
        URL url = new URL(s);
        Image image = ImageIO.read(url);
        imageLabel.setIcon(new ImageIcon(image));
    }
    
    public void addItemIdComboBox(String item){
        this.idComboBox.addItem(item);
    }
    
    public String getItemIdComboBox(){
       return this.idComboBox.getSelectedItem().toString();
    }
    
    public void addIdComboBoxActionListener (ActionListener al){
        this.idComboBox.addActionListener(al);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel genderLabel;
    private javax.swing.JComboBox<String> idComboBox;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel originLabel;
    private javax.swing.JLabel speciesLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
