/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.personaje;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author dam2_alu08@inf.ald
 */
public class PersonajeDialog extends javax.swing.JDialog {
    /**
     * Creates new form PersonajeDialog
     */
    private JTextField idEliminar;
    private JTextField idModificar;
    
    public PersonajeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(new Color(0,0,0));
        idComboBox.setBackground(new Color(116,253,131));
        addPersonajeButton.setBackground(new Color(116,253,131));
        deletePersonajeButton.setBackground(new Color(116,253,131));
        modifyPersonajeButton.setBackground(new Color(116,253,131));
        
        idEliminar = new JTextField(5);
        idEliminar.setBackground(new Color(116,253,131));
        getContentPane().add(idEliminar);
        idEliminar.setBounds(540,20,50,25);
        
        UIManager.put("ToolTip.background", new Color(116, 253, 131));
        UIManager.put("ToolTip.foreground", Color.BLACK);
        UIManager.put("ToolTip.border", javax.swing.BorderFactory.createLineBorder(Color.BLACK));
        
        idEliminar.setToolTipText("Introduce el ID a eliminar");
        
        idModificar = new JTextField(5);
        idModificar.setBackground(new Color(116,253,131));
        getContentPane().add(idModificar);
        idModificar.setBounds(540,53,50,25);
        
        idModificar.setToolTipText("Introduce el ID a modificar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked");
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idComboBox = new javax.swing.JComboBox<>();
        imageLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        speciesLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        originLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        nameLabel2 = new javax.swing.JLabel();
        statusLabel2 = new javax.swing.JLabel();
        speciesLabel2 = new javax.swing.JLabel();
        typeLabel2 = new javax.swing.JLabel();
        genderLabel2 = new javax.swing.JLabel();
        originLabel2 = new javax.swing.JLabel();
        locationLabel2 = new javax.swing.JLabel();
        addPersonajeButton = new javax.swing.JButton();
        deletePersonajeButton = new javax.swing.JButton();
        modifyPersonajeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        idComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComboBoxActionPerformed(evt);
            }
        });

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        imageLabel.setText(" ");

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText(" ");

        statusLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(255, 255, 255));
        statusLabel.setText(" ");

        speciesLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        speciesLabel.setForeground(new java.awt.Color(255, 255, 255));
        speciesLabel.setText(" ");

        typeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(255, 255, 255));
        typeLabel.setText(" ");

        genderLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel.setText(" ");

        originLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        originLabel.setForeground(new java.awt.Color(255, 255, 255));
        originLabel.setText(" ");

        locationLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        locationLabel.setForeground(new java.awt.Color(255, 255, 255));
        locationLabel.setText(" ");

        idLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Id.png"))); // NOI18N
        idLabel.setText("jLabel1");
        idLabel.setMaximumSize(new java.awt.Dimension(511, 796));

        nameLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Nombre.png"))); // NOI18N
        nameLabel2.setText("nombre");

        statusLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Estado.png"))); // NOI18N
        statusLabel2.setText("estado");

        speciesLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Especie.png"))); // NOI18N
        speciesLabel2.setText("especie");

        typeLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tipo.png"))); // NOI18N
        typeLabel2.setText("tipo");

        genderLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Genero.png"))); // NOI18N
        genderLabel2.setText("genero");

        originLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Origen.png"))); // NOI18N
        originLabel2.setText("origen");

        locationLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Localizacion.png"))); // NOI18N
        locationLabel2.setText("localizacion");

        addPersonajeButton.setText("Añadir Personaje");
        addPersonajeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersonajeButtonActionPerformed(evt);
            }
        });

        deletePersonajeButton.setText("Eliminar Personaje");

        modifyPersonajeButton.setText("Modificar Personaje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(imageLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameLabel)
                                .addComponent(typeLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(modifyPersonajeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deletePersonajeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addPersonajeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(genderLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(speciesLabel)
                                        .addComponent(speciesLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(statusLabel)
                                            .addComponent(statusLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(typeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)))))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(locationLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(originLabel))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(locationLabel)
                                .addComponent(originLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(142, 142, 142))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(imageLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nameLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameLabel)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(locationLabel)
                                .addGap(18, 18, 18)
                                .addComponent(originLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(originLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(genderLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(typeLabel2)
                                        .addComponent(locationLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(typeLabel)
                                    .addComponent(genderLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(speciesLabel2)
                                    .addComponent(statusLabel2))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(speciesLabel)
                                    .addComponent(statusLabel)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addPersonajeButton)
                        .addGap(8, 8, 8)
                        .addComponent(deletePersonajeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modifyPersonajeButton)))
                .addContainerGap(213, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idComboBoxActionPerformed

    private void addPersonajeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersonajeButtonActionPerformed

    }//GEN-LAST:event_addPersonajeButtonActionPerformed

    public void statusIdModificar(boolean b){
        this.idModificar.setVisible(b);
    }
    
    public void statusIdEliminar(boolean b){
        this.idEliminar.setVisible(b);
    }
    
    public void statusAddPersonajeButton(boolean b){
        this.addPersonajeButton.setVisible(b);
    }
    
    public void statusDeletePersonajeButton(boolean b){
        this.deletePersonajeButton.setVisible(b);
    }
    
    public void statusModifyPersonajeButton(boolean b){
        this.modifyPersonajeButton.setVisible(b);
    }
    public void setTextNameLabel(String s) {
        this.nameLabel.setText(s);
    }

    public void setTextStatusLabel(String s) {
        this.statusLabel.setText(s);
    }

    public void setTextSpeciesLabel(String s) {
        this.speciesLabel.setText(s);
    }

    public void setTextTypeLabel(String s) {
        this.typeLabel.setText(s);
    }
    
    public void setTextGenderLabel(String s) {
        this.genderLabel.setText(s);
    }
    
    public void setTextOriginLabel(String s) {
        this.originLabel.setText(s);
    }
    
    public void setTextLocationLabel(String s) {
        this.locationLabel.setText(s);
    }
    
    public void setIconImageLabel(String s) throws IOException{
        URL url = new URL(s);
        Image image = ImageIO.read(url);
        imageLabel.setIcon(new ImageIcon(image));
        int alto = 200;
        int ancho = 200;
        Image imagenRedimensionada = image.getScaledInstance(alto, ancho, Image.SCALE_SMOOTH);
        imageLabel.setIcon(new ImageIcon(imagenRedimensionada));
    }
    
    public void addItemIdComboBox(String item){
        this.idComboBox.addItem(item);
    }
    
    public String getItemIdComboBox(){
       return this.idComboBox.getSelectedItem().toString();
    }
    
    public void addIdComboBoxActionListener (ActionListener al){
        this.idComboBox.addActionListener(al);
    }
    
    public void addPersonajesListener(ActionListener al) {
        this.addPersonajeButton.addActionListener(al);
    }
    
    public void addDeletePersonajeButtonListener(ActionListener al) {
        this.deletePersonajeButton.addActionListener(al);
    }
    
    public String getIdEliminar() {
        return idEliminar.getText();
    }
    
    public void addModifyPersonajeButtonListener(ActionListener al) {
        this.modifyPersonajeButton.addActionListener(al);
    }
    
    public String getIdModificar() {
        return idModificar.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPersonajeButton;
    private javax.swing.JButton deletePersonajeButton;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel genderLabel2;
    private javax.swing.JComboBox<String> idComboBox;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel locationLabel2;
    private javax.swing.JButton modifyPersonajeButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel originLabel;
    private javax.swing.JLabel originLabel2;
    private javax.swing.JLabel speciesLabel;
    private javax.swing.JLabel speciesLabel2;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel statusLabel2;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel typeLabel2;
    // End of variables declaration//GEN-END:variables

}
